import { QAPost, ScheduledSession, Tutor, TutoringRequest } from "./types";

export const SUBJECTS = [
  "AP Chemistry",
  "AP Biology",
  "Chemistry",
  "Biology",
  "Algebra 2",
  "Geometry",
  "Precalculus",
  "AP Calculus AB",
  "AP Calculus BC",
  "AP Statistics",
  "AP Physics 1",
  "Physics",
  "AP Computer Science A",
  "AP US History",
  "World History",
  "AP English Language",
  "English 10",
  "Spanish 3",
  "AP Spanish Language",
  "Mandarin 2",
];

export const PERIODS = [
  "Access Period",
  "B-Period (Commons)",
  "Lunch (Commons)",
  "After School",
] as const;

export const TUTORS: Tutor[] = [
  {
    id: "t1",
    name: "Ananya Krishnan",
    grade: 12,
    subjects: ["AP Chemistry", "Chemistry", "AP Biology"],
    approvedSubjects: ["AP Chemistry", "Chemistry", "AP Biology"],
    periods: ["Access Period", "B-Period (Commons)"],
    bio: "4th-year AL tutor, TA for Honors Chem. Loves stoichiometry.",
    sessionsThisMonth: 14,
    hoursThisMonth: 9.5,
    rating: 4.9,
    active: true,
  },
  {
    id: "t2",
    name: "Marcus Webb",
    grade: 11,
    subjects: ["Algebra 2", "Geometry", "Precalculus"],
    approvedSubjects: ["Algebra 2", "Geometry", "Precalculus"],
    periods: ["B-Period (Commons)", "Lunch (Commons)"],
    bio: "Math team captain, specializes in algebra fundamentals.",
    sessionsThisMonth: 11,
    hoursThisMonth: 7,
    rating: 4.7,
    active: true,
  },
  {
    id: "t3",
    name: "Priya Nair",
    grade: 12,
    subjects: ["AP Calculus BC", "AP Calculus AB", "Precalculus"],
    approvedSubjects: ["AP Calculus BC", "AP Calculus AB", "Precalculus"],
    periods: ["Access Period"],
    bio: "Peer tutor since sophomore year, calc BC student.",
    sessionsThisMonth: 8,
    hoursThisMonth: 5.5,
    rating: 5.0,
    active: true,
  },
  {
    id: "t4",
    name: "Diego Alvarez",
    grade: 11,
    subjects: ["AP Physics 1", "Physics", "AP Calculus AB"],
    approvedSubjects: ["AP Physics 1", "Physics", "AP Calculus AB"],
    periods: ["B-Period (Commons)", "After School"],
    bio: "Physics olympiad participant, enjoys visual explanations.",
    sessionsThisMonth: 6,
    hoursThisMonth: 4,
    rating: 4.6,
    active: true,
  },
  {
    id: "t5",
    name: "Chloe Tanaka",
    grade: 12,
    subjects: ["AP English Language", "English 10"],
    approvedSubjects: ["AP English Language", "English 10"],
    periods: ["Access Period", "Lunch (Commons)"],
    bio: "Writing center volunteer, strong at essay structure feedback.",
    sessionsThisMonth: 12,
    hoursThisMonth: 8,
    rating: 4.8,
    active: true,
  },
  {
    id: "t6",
    name: "Jason Park",
    grade: 10,
    subjects: ["Algebra 2", "Geometry"],
    approvedSubjects: ["Geometry"],
    periods: ["Lunch (Commons)"],
    bio: "New AL member, strong foundation in freshman/sophomore math.",
    sessionsThisMonth: 3,
    hoursThisMonth: 2,
    rating: 4.5,
    active: true,
  },
  {
    id: "t7",
    name: "Sofia Ibarra",
    grade: 12,
    subjects: ["AP Spanish Language", "Spanish 3"],
    approvedSubjects: ["AP Spanish Language", "Spanish 3"],
    periods: ["Access Period", "B-Period (Commons)"],
    bio: "Heritage Spanish speaker, helps with oral proficiency practice.",
    sessionsThisMonth: 5,
    hoursThisMonth: 3.5,
    rating: 4.9,
    active: true,
  },
  {
    id: "t8",
    name: "Ethan Zhou",
    grade: 11,
    subjects: ["AP Computer Science A", "AP Calculus AB"],
    approvedSubjects: ["AP Computer Science A", "AP Calculus AB"],
    periods: ["B-Period (Commons)", "After School"],
    bio: "Builds side projects, patient with debugging walk-throughs.",
    sessionsThisMonth: 9,
    hoursThisMonth: 6,
    rating: 4.8,
    active: true,
  },
  {
    id: "t9",
    name: "Grace Lin",
    grade: 12,
    subjects: ["AP Biology", "Biology", "AP Chemistry"],
    approvedSubjects: ["AP Biology", "Biology", "AP Chemistry"],
    periods: ["Access Period"],
    bio: "Aspiring pre-med, tutors bio and chem together well.",
    sessionsThisMonth: 10,
    hoursThisMonth: 6.5,
    rating: 4.7,
    active: true,
  },
  {
    id: "t10",
    name: "Liam O'Connor",
    grade: 11,
    subjects: ["AP US History", "World History"],
    approvedSubjects: ["AP US History", "World History"],
    periods: ["Lunch (Commons)", "After School"],
    bio: "History bowl member, great at document-based question prep.",
    sessionsThisMonth: 4,
    hoursThisMonth: 3,
    rating: 4.6,
    active: true,
  },
  {
    id: "t11",
    name: "Isabella Ruiz",
    grade: 12,
    subjects: ["AP Statistics", "Algebra 2"],
    approvedSubjects: ["AP Statistics", "Algebra 2"],
    periods: ["Access Period", "Lunch (Commons)"],
    bio: "Stats TA, explains concepts with real datasets.",
    sessionsThisMonth: 7,
    hoursThisMonth: 5,
    rating: 4.8,
    active: true,
  },
  {
    id: "t12",
    name: "Noah Kim",
    grade: 10,
    subjects: ["Geometry", "Algebra 2"],
    approvedSubjects: ["Geometry"],
    periods: ["B-Period (Commons)"],
    bio: "First-year tutor, enthusiastic and reliable.",
    sessionsThisMonth: 2,
    hoursThisMonth: 1.5,
    rating: 4.4,
    active: true,
  },
  {
    id: "t13",
    name: "Mia Chen",
    grade: 12,
    subjects: ["AP Computer Science A", "AP Statistics"],
    approvedSubjects: ["AP Computer Science A", "AP Statistics"],
    periods: ["Access Period", "After School"],
    bio: "CS club president, tutors both AP CS sections.",
    sessionsThisMonth: 8,
    hoursThisMonth: 5.5,
    rating: 4.9,
    active: true,
  },
  {
    id: "t14",
    name: "Aarav Mehta",
    grade: 11,
    subjects: ["Physics", "AP Physics 1", "Precalculus"],
    approvedSubjects: ["Physics", "AP Physics 1", "Precalculus"],
    periods: ["Lunch (Commons)"],
    bio: "Enjoys breaking down free-body diagrams step by step.",
    sessionsThisMonth: 5,
    hoursThisMonth: 3.5,
    rating: 4.6,
    active: true,
  },
  {
    id: "t15",
    name: "Emma Davies",
    grade: 12,
    subjects: ["English 10", "AP English Language", "World History"],
    approvedSubjects: ["English 10", "AP English Language", "World History"],
    periods: ["Access Period", "B-Period (Commons)"],
    bio: "Literary magazine editor, strong at essay revision.",
    sessionsThisMonth: 9,
    hoursThisMonth: 6,
    rating: 4.8,
    active: true,
  },
  {
    id: "t16",
    name: "Ryan Foster",
    grade: 11,
    subjects: ["Mandarin 2", "Algebra 2"],
    approvedSubjects: ["Mandarin 2"],
    periods: ["After School"],
    bio: "Bilingual tutor, also helps with math homework.",
    sessionsThisMonth: 3,
    hoursThisMonth: 2,
    rating: 4.5,
    active: true,
  },
  {
    id: "t17",
    name: "Zoe Patel",
    grade: 12,
    subjects: ["AP Chemistry", "AP Calculus AB"],
    approvedSubjects: ["AP Chemistry", "AP Calculus AB"],
    periods: ["Access Period", "Lunch (Commons)"],
    bio: "Balances two of the highest-demand subjects on campus.",
    sessionsThisMonth: 13,
    hoursThisMonth: 9,
    rating: 4.9,
    active: true,
  },
  {
    id: "t18",
    name: "Lucas Bennett",
    grade: 10,
    subjects: ["Geometry", "Biology"],
    approvedSubjects: ["Geometry"],
    periods: ["B-Period (Commons)", "Lunch (Commons)"],
    bio: "Sophomore tutor pairing well with underclassmen.",
    sessionsThisMonth: 4,
    hoursThisMonth: 3,
    rating: 4.5,
    active: true,
  },
];

// Fixed anchor (rather than `new Date()`) so seed timestamps are identical on
// every render — using "now" here would differ between server and client and
// break hydration.
export const DEMO_TODAY = new Date("2026-09-13T16:00:00Z");

const daysAgo = (n: number) => {
  const d = new Date(DEMO_TODAY);
  d.setDate(d.getDate() - n);
  return d.toISOString();
};

const daysFromNow = (n: number) => {
  const d = new Date(DEMO_TODAY);
  d.setDate(d.getDate() + n);
  return d.toISOString().slice(0, 10);
};

export const REQUESTS: TutoringRequest[] = [
  {
    id: "r1",
    requesterName: "Sam Patterson",
    requesterType: "Student",
    subject: "AP Chemistry",
    period: "Access Period",
    source: "Infinite Campus",
    notes: "Struggling with equilibrium constant problems, unit 6.",
    status: "open",
    createdAt: daysAgo(0),
  },
  {
    id: "r2",
    requesterName: "Mr. Alvarado (Chemistry)",
    requesterType: "Teacher",
    subject: "Chemistry",
    period: "B-Period (Commons)",
    source: "Teacher Google Form",
    notes: "Requesting a tutor for period 3 class, 2 students need review before test Friday.",
    status: "open",
    createdAt: daysAgo(0),
  },
  {
    id: "r3",
    requesterName: "Jordan Lee",
    requesterType: "Student",
    subject: "AP Calculus BC",
    period: "Access Period",
    source: "Infinite Campus",
    notes: "Related rates and implicit differentiation.",
    status: "assigned",
    assignedTutorId: "t3",
    createdAt: daysAgo(1),
  },
  {
    id: "r4",
    requesterName: "Taylor Nguyen",
    requesterType: "Student",
    subject: "Algebra 2",
    period: "Lunch (Commons)",
    source: "Infinite Campus",
    notes: "Systems of equations, wants weekly recurring help.",
    status: "assigned",
    assignedTutorId: "t2",
    createdAt: daysAgo(2),
  },
  {
    id: "r5",
    requesterName: "Ms. Whitfield (World History)",
    requesterType: "Teacher",
    subject: "World History",
    period: "B-Period (Commons)",
    source: "Teacher Google Form",
    notes: "In-class support for 4 students behind on DBQ essay drafts.",
    status: "open",
    createdAt: daysAgo(1),
  },
  {
    id: "r6",
    requesterName: "Olivia Martinez",
    requesterType: "Student",
    subject: "AP Statistics",
    period: "Access Period",
    source: "Infinite Campus",
    notes: "Hypothesis testing review before unit exam.",
    status: "open",
    createdAt: daysAgo(0),
  },
  {
    id: "r7",
    requesterName: "Ben Carter",
    requesterType: "Student",
    subject: "AP Physics 1",
    period: "B-Period (Commons)",
    source: "Infinite Campus",
    notes: "Rotational motion, needs conceptual walkthrough.",
    status: "assigned",
    assignedTutorId: "t4",
    createdAt: daysAgo(3),
  },
  {
    id: "r8",
    requesterName: "Grace Osei",
    requesterType: "Student",
    subject: "AP Spanish Language",
    period: "Access Period",
    source: "Infinite Campus",
    notes: "Oral presentation practice for the AP exam.",
    status: "completed",
    assignedTutorId: "t7",
    createdAt: daysAgo(6),
  },
  {
    id: "r9",
    requesterName: "Mr. Delgado (Geometry)",
    requesterType: "Teacher",
    subject: "Geometry",
    period: "Lunch (Commons)",
    source: "Teacher Google Form",
    notes: "Small group re-teach on triangle congruence proofs.",
    status: "completed",
    assignedTutorId: "t6",
    createdAt: daysAgo(7),
  },
  {
    id: "r10",
    requesterName: "Henry Wu",
    requesterType: "Student",
    subject: "AP Computer Science A",
    period: "After School",
    source: "Infinite Campus",
    notes: "Recursion and array-based debugging help.",
    status: "open",
    createdAt: daysAgo(0),
  },
  {
    id: "r11",
    requesterName: "Natalie Brooks",
    requesterType: "Student",
    subject: "English 10",
    period: "Access Period",
    source: "Infinite Campus",
    notes: "Essay outline feedback, argumentative essay unit.",
    status: "assigned",
    assignedTutorId: "t15",
    createdAt: daysAgo(2),
  },
  {
    id: "r12",
    requesterName: "Aiden Scott",
    requesterType: "Student",
    subject: "AP Biology",
    period: "B-Period (Commons)",
    source: "Infinite Campus",
    notes: "Cellular respiration and photosynthesis unit review.",
    status: "completed",
    assignedTutorId: "t9",
    createdAt: daysAgo(5),
  },
];

export const SCHEDULED_SESSIONS: ScheduledSession[] = [
  {
    id: "s1",
    tutorId: "t1",
    subject: "AP Chemistry",
    period: "Access Period",
    date: daysFromNow(1),
    location: "Room 214",
    capacity: 6,
    joinedStudents: ["Maya Torres", "Devon Clarke"],
    notes: "Unit 6 equilibrium review — bring your ICE table practice set.",
    createdAt: daysAgo(1),
  },
  {
    id: "s2",
    tutorId: "t3",
    subject: "AP Calculus BC",
    period: "Access Period",
    date: daysFromNow(2),
    location: "Library Study Room 2",
    capacity: 4,
    joinedStudents: ["Jordan Lee", "Kevin Park", "Amara Osei", "Ian Fitzgerald"],
    notes: "Related rates + implicit differentiation practice.",
    createdAt: daysAgo(1),
  },
  {
    id: "s3",
    tutorId: "t8",
    subject: "AP Computer Science A",
    period: "B-Period (Commons)",
    date: daysFromNow(2),
    location: "Commons — Table 3",
    capacity: 5,
    joinedStudents: ["Henry Wu"],
    createdAt: daysAgo(1),
  },
  {
    id: "s4",
    tutorId: "t2",
    subject: "Algebra 2",
    period: "Lunch (Commons)",
    date: daysFromNow(3),
    location: "Commons — Table 1",
    capacity: 8,
    joinedStudents: [],
    createdAt: daysAgo(0),
  },
  {
    id: "s5",
    tutorId: "t17",
    subject: "AP Chemistry",
    period: "Lunch (Commons)",
    date: daysFromNow(4),
    location: "Room 118",
    capacity: 6,
    joinedStudents: ["Ravi Subramaniam"],
    createdAt: daysAgo(0),
  },
  {
    id: "s6",
    tutorId: "t11",
    subject: "AP Statistics",
    period: "Access Period",
    date: daysFromNow(3),
    location: "Room 220",
    capacity: 5,
    joinedStudents: ["Olivia Martinez", "Grace Osei"],
    notes: "Hypothesis testing walkthrough before the unit exam.",
    createdAt: daysAgo(1),
  },
  {
    id: "s7",
    tutorId: "t5",
    subject: "English 10",
    period: "Access Period",
    date: daysFromNow(1),
    location: "Writing Center",
    capacity: 6,
    joinedStudents: [],
    createdAt: daysAgo(0),
  },
];

export const QA_POSTS: QAPost[] = [
  {
    id: "q1",
    subject: "AP Chemistry",
    authorName: "Sam Patterson",
    question:
      "After my Access session I'm still stuck on ICE tables when Kc is very small — is there a shortcut for deciding when to approximate x as negligible?",
    createdAt: daysAgo(0),
    resolved: true,
    replies: [
      {
        id: "q1r1",
        authorName: "Ananya Krishnan",
        authorType: "Tutor",
        text: "Good question! Rule of thumb: if Kc is smaller than about 10^-3 relative to initial concentration, you can usually assume x is negligible in the denominator — but always check by plugging x back in and seeing if it changes the answer by <5%. Bring your specific problem to Access tomorrow and we'll verify it together.",
        createdAt: daysAgo(0),
      },
    ],
  },
  {
    id: "q2",
    subject: "AP Calculus BC",
    authorName: "Jordan Lee",
    question: "For related rates, how do I know which variable to differentiate with respect to time first?",
    createdAt: daysAgo(1),
    resolved: false,
    replies: [
      {
        id: "q2r1",
        authorName: "Priya Nair",
        authorType: "Tutor",
        text: "Start by writing the equation that relates all the quantities that are changing, then differentiate the whole equation implicitly with respect to t — you don't pick one variable, every variable that depends on time gets a d/dt. Send me the specific problem and I'll mark it up.",
        createdAt: daysAgo(1),
      },
    ],
  },
  {
    id: "q3",
    subject: "Algebra 2",
    authorName: "Taylor Nguyen",
    question: "Quick follow-up from lunch — for systems of 3 equations, is elimination always faster than substitution?",
    createdAt: daysAgo(2),
    resolved: false,
    replies: [],
  },
  {
    id: "q4",
    subject: "AP Physics 1",
    authorName: "Ben Carter",
    question: "When a problem says 'rolling without slipping,' which formulas connect linear and angular velocity again?",
    createdAt: daysAgo(3),
    resolved: true,
    replies: [
      {
        id: "q4r1",
        authorName: "Diego Alvarez",
        authorType: "Tutor",
        text: "v = ωr and a = αr — those two are your bridge between linear and angular any time you see 'rolling without slipping.' Also remember the friction there is static, not kinetic, since the contact point isn't sliding.",
        createdAt: daysAgo(3),
      },
    ],
  },
  {
    id: "q5",
    subject: "AP Computer Science A",
    authorName: "Henry Wu",
    question: "My recursive method works for small inputs but stack overflows on large arrays — is that just expected for recursion?",
    createdAt: daysAgo(0),
    resolved: false,
    replies: [],
  },
  {
    id: "q6",
    subject: "AP Statistics",
    authorName: "Olivia Martinez",
    question: "What's the actual difference between a Type I and Type II error in plain English? The textbook definition isn't sticking.",
    createdAt: daysAgo(1),
    resolved: true,
    replies: [
      {
        id: "q6r1",
        authorName: "Isabella Ruiz",
        authorType: "Tutor",
        text: "Type I = you reject a true null (false alarm, you cried wolf). Type II = you fail to reject a false null (you missed a real effect). I like to think of it like a smoke alarm: Type I is the alarm going off when there's no fire, Type II is the alarm staying silent during an actual fire.",
        createdAt: daysAgo(1),
      },
    ],
  },
];
